language: scala
scala:
   - 2.11.8
   - 2.11.11
   - 2.12.3
   - 2.12.4
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)